apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: route-management-kv-secrets
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: "ffbb5ff4-406a-494f-8de9-9776e768f1ed"
    keyvaultName: "ds-gtbs-kv-prod"
    tenantId: "d595be8d-b306-45f4-8064-9e5b82fbe52b"
    objects: |
      array:
        - |
          objectName: route-datasource-url
          objectType: secret
        - |
          objectName: route-datasource-username
          objectType: secret
        - |
          objectName: route-datasource-password
          objectType: secret
        - |
          objectName: spring-data-redis-host
          objectType: secret
        - |
          objectName: spring-data-redis-port
          objectType: secret
        - |
          objectName: spring-data-redis-password
          objectType: secret
        - |
          objectName: spring-kafka-bootstrap-servers
          objectType: secret
  secretObjects:
    - secretName: route-management-kv-synced
      type: Opaque
      data:
        - objectName: route-datasource-url
          key: ROUTE_DATASOURCE_URL
        - objectName: route-datasource-username
          key: ROUTE_DATASOURCE_USERNAME
        - objectName: route-datasource-password
          key: ROUTE_DATASOURCE_PASSWORD
        - objectName: spring-data-redis-host
          key: SPRING_DATA_REDIS_HOST
        - objectName: spring-data-redis-port
          key: SPRING_DATA_REDIS_PORT
        - objectName: spring-data-redis-password
          key: SPRING_DATA_REDIS_PASSWORD
        - objectName: spring-kafka-bootstrap-servers
          key: SPRING_KAFKA_BOOTSTRAP_SERVERS
